import json
import contextlib
import importlib.util
import os
import re
import subprocess
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from http.cookies import SimpleCookie
from pathlib import Path
from urllib.parse import urlsplit

from .config import CFG
from .import_targets import import_account_session, target_label
from .paths import output_dir, runtime_dir
from .storage import upsert_account

TEAM_CHANNEL_CHATGPT = "chatgpt_team"
TEAM_CHANNEL_KYL_PROTOCOL = "kyl_protocol"


def default_team_script_path():
    return str(Path(__file__).resolve().parent.parent / "scripts" / "ChatGPT_team.py")


def default_kyl_runner_dir():
    return str(Path(__file__).resolve().parent.parent / "scripts" / "kyl_protocol_runner")


def default_kyl_replay_script_path():
    return str(Path(default_kyl_runner_dir()) / "kyl_protocol_replay.py")


def default_kyl_state_path():
    return str(Path(default_kyl_runner_dir()) / "kyl_state.json")


def import_team_tokens(
    token_dir="",
    token_files=None,
    token_file_list="",
    target="cpa",
    export_dir="",
    workers=1,
    cpa_api_url="",
    cpa_api_token="",
    sub2api_url="",
    sub2api_token="",
    sub2api_email="",
    sub2api_password="",
    sub2api_group="",
    sub2api_group_ids=None,
    sub2api_proxy="",
    sub2api_proxy_id=None,
    sub2api_priority=None,
    sub2api_concurrency=None,
    cleanup=True,
    source="ChatGPT_team.py",
):
    """Import Codex token JSONs generated by a Team Token channel into CPA/SUB2API."""

    files = discover_team_token_files(
        token_dir=token_dir,
        token_files=token_files,
        token_file_list=token_file_list,
    )
    if not files:
        return {"ok": False, "error": "no_team_token_files", "total": 0, "results": []}

    normalized_dir = _normalized_dir(export_dir)
    ordered = [None] * len(files)
    max_workers = max(1, min(int(workers or 1), 4, len(files)))

    def _run(index, path):
        try:
            return index, import_team_token_file(
                path,
                target=target,
                normalized_dir=normalized_dir,
                export_dir=export_dir,
                cpa_api_url=cpa_api_url,
                cpa_api_token=cpa_api_token,
                sub2api_url=sub2api_url,
                sub2api_token=sub2api_token,
                sub2api_email=sub2api_email,
                sub2api_password=sub2api_password,
                sub2api_group=sub2api_group,
                sub2api_group_ids=sub2api_group_ids,
                sub2api_proxy=sub2api_proxy,
                sub2api_proxy_id=sub2api_proxy_id,
                sub2api_priority=sub2api_priority,
                sub2api_concurrency=sub2api_concurrency,
                source=source,
            )
        except Exception as exc:
            return index, {"ok": False, "path": str(path), "error": str(exc)}

    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = [executor.submit(_run, i, path) for i, path in enumerate(files)]
        for future in as_completed(futures):
            index, result = future.result()
            ordered[index] = result

    results = [item for item in ordered if item is not None]
    ok_count = sum(1 for item in results if item.get("ok"))
    return {
        "ok": ok_count == len(results),
        "target": target_label(target),
        "total": len(results),
        "success": ok_count,
        "failed": len(results) - ok_count,
        "results": results,
    }


def run_team_script_and_import(
    script_path,
    total=1,
    script_workers=1,
    proxy="",
    output="registered_only.txt",
    timeout=1800,
    target="cpa",
    export_dir="",
    workers=1,
    cpa_api_url="",
    cpa_api_token="",
    sub2api_url="",
    sub2api_token="",
    sub2api_email="",
    sub2api_password="",
    sub2api_group="",
    sub2api_group_ids=None,
    sub2api_proxy="",
    sub2api_proxy_id=None,
    sub2api_priority=None,
    sub2api_concurrency=None,
    cleanup=True,
):
    script = Path(script_path).expanduser()
    if not script.exists() or not script.is_file():
        return {"ok": False, "error": "team_script_not_found", "script": str(script)}
    total = max(1, int(total or 1))
    script_workers = max(1, int(script_workers or 1))
    timeout = max(60, int(timeout or 1800))
    script_cwd = script.parent
    token_dir = script_cwd / "codex_tokens"
    before = _snapshot_token_files(token_dir)
    started = time.time()

    cmd = [
        sys.executable,
        str(script),
        "--total",
        str(total),
        "--workers",
        str(script_workers),
        "--output",
        str(output or "registered_only.txt"),
    ]
    if proxy:
        cmd.extend(["--proxy", str(proxy)])

    print("[*] Running ChatGPT_team.py: " + " ".join(_quote_arg(part) for part in cmd), flush=True)
    env = os.environ.copy()
    if proxy:
        env.setdefault("PROXY", str(proxy))
    proc = subprocess.Popen(
        cmd,
        cwd=str(script_cwd),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        encoding="utf-8",
        errors="replace",
        env=env,
    )
    output_lines = []
    try:
        deadline = time.time() + timeout
        while True:
            if proc.stdout is not None:
                line = proc.stdout.readline()
                if line:
                    line = line.rstrip("\r\n")
                    output_lines.append(line)
                    print("[team] " + line, flush=True)
            if proc.poll() is not None:
                if proc.stdout is not None:
                    for line in proc.stdout:
                        line = line.rstrip("\r\n")
                        output_lines.append(line)
                        print("[team] " + line, flush=True)
                break
            if time.time() > deadline:
                proc.kill()
                cleanup_result = cleanup_team_runtime_files(script_cwd) if cleanup else {"ok": True, "removed": []}
                return {
                    "ok": False,
                    "error": "team_script_timeout",
                    "script": str(script),
                    "timeout": timeout,
                    "cleanup": cleanup_result,
                    "output_tail": output_lines[-20:],
                }
            if not line:
                time.sleep(0.1)
    finally:
        with contextlib.suppress(Exception):
            if proc.stdout is not None:
                proc.stdout.close()

    exit_code = int(proc.returncode or 0)
    after_files = _changed_token_files(token_dir, before, started)
    if not after_files and token_dir.exists():
        after_files = sorted(token_dir.glob("*.json"))
    cleanup_result = {"ok": True, "removed": []}
    import_result = {"ok": False, "error": "import_not_started"}
    try:
        import_result = import_team_tokens(
            token_files=after_files,
            target=target,
            export_dir=export_dir,
            workers=workers,
            cpa_api_url=cpa_api_url,
            cpa_api_token=cpa_api_token,
            sub2api_url=sub2api_url,
            sub2api_token=sub2api_token,
            sub2api_email=sub2api_email,
            sub2api_password=sub2api_password,
            sub2api_group=sub2api_group,
            sub2api_group_ids=sub2api_group_ids,
            sub2api_proxy=sub2api_proxy,
            sub2api_proxy_id=sub2api_proxy_id,
            sub2api_priority=sub2api_priority,
            sub2api_concurrency=sub2api_concurrency,
            source="ChatGPT_team.py",
        )
    finally:
        if cleanup:
            cleanup_result = cleanup_team_runtime_files(script_cwd)
    return {
        "ok": exit_code == 0 and bool(import_result.get("ok")),
        "script": str(script),
        "exit_code": exit_code,
        "generated_token_files": [str(path) for path in after_files],
        "import": import_result,
        "cleanup": cleanup_result,
        "output_tail": output_lines[-20:],
    }


def run_kyl_protocol_and_import(
    state_path,
    cookie_path="",
    har_path="",
    fingerprint="",
    total=1,
    protocol_workers=1,
    start=0,
    timeout=1800,
    runner_dir="",
    runtime_path="",
    auth_dir="",
    include_existing=False,
    proxy="",
    target="cpa",
    export_dir="",
    workers=1,
    cpa_api_url="",
    cpa_api_token="",
    sub2api_url="",
    sub2api_token="",
    sub2api_email="",
    sub2api_password="",
    sub2api_group="",
    sub2api_group_ids=None,
    sub2api_proxy="",
    sub2api_proxy_id=None,
    sub2api_priority=None,
    sub2api_concurrency=None,
    cleanup=True,
):
    runner_root = Path(runner_dir or default_kyl_runner_dir()).expanduser().resolve()
    batch_script = runner_root / "run_kyl_protocol_batch.js"
    replay_script = runner_root / "kyl_protocol_replay.py"
    if not batch_script.exists() or not batch_script.is_file():
        return {"ok": False, "error": "kyl_batch_script_not_found", "script": str(batch_script)}
    if not replay_script.exists() or not replay_script.is_file():
        return {"ok": False, "error": "kyl_replay_script_not_found", "script": str(replay_script)}

    state = Path(str(state_path or default_kyl_state_path())).expanduser()
    if not state.exists() or not state.is_file():
        return {"ok": False, "error": "kyl_state_not_found", "state": str(state)}
    state_data = _read_json(state)
    if not isinstance(state_data.get("accounts"), list) or not state_data.get("accounts"):
        return {
            "ok": False,
            "error": "kyl_state_no_accounts",
            "state": str(state),
            "message": "KYL STATE_PATH must contain accounts with email and sub.",
        }

    runtime_root = Path(runtime_path or (runtime_dir(CFG) / "kyl_protocol")).expanduser().resolve()
    runtime_root.mkdir(parents=True, exist_ok=True)
    auth_root = Path(auth_dir or (runtime_root / "auths")).expanduser().resolve()
    auth_root.mkdir(parents=True, exist_ok=True)
    status_path = runtime_root / "protocol-batch.jsonl"
    cookie_info = _prepare_kyl_cookie_path(cookie_path=cookie_path, har_path=har_path, runtime_root=runtime_root)
    embedded_defaults = _load_embedded_kyl_defaults()
    if not cookie_info.get("path") and embedded_defaults.get("cookies"):
        cookie_info = _write_embedded_kyl_cookies(embedded_defaults, runtime_root)
    effective_fingerprint = str(fingerprint or cookie_info.get("fingerprint") or embedded_defaults.get("fingerprint") or "").strip()

    total = max(1, int(total or 1))
    protocol_workers = max(1, int(protocol_workers or 1))
    start = max(0, int(start or 0))
    timeout = max(60, int(timeout or 1800))
    before = _snapshot_token_files(auth_root)
    started = time.time()

    cmd = [
        _node_executable(),
        str(batch_script),
        "--state",
        str(state),
        "--auth-dir",
        str(auth_root),
        "--replay-script",
        str(replay_script),
        "--python",
        sys.executable,
        "--start",
        str(start),
        "--limit",
        str(total),
        "--workers",
        str(protocol_workers),
        "--status",
        str(status_path),
    ]
    if cookie_info.get("path"):
        cmd.extend(["--cookies", str(cookie_info["path"])])
    if effective_fingerprint:
        cmd.extend(["--fingerprint", effective_fingerprint])
    if include_existing:
        cmd.append("--include-existing=1")

    print("[*] Running KYL protocol channel: " + " ".join(_quote_arg(part) for part in _sanitize_kyl_command(cmd)), flush=True)
    env = os.environ.copy()
    env.setdefault("KYL_PROTOCOL_RUNTIME", str(runtime_root))
    env.setdefault("WORK_DIR", str(runtime_root))
    env.setdefault("AUTH_DIR", str(auth_root))
    env.setdefault("DIRECT_CODEX_SAVE", "1")
    env.setdefault("CASDOOR_BRIDGE", "kyl")
    if cookie_info.get("path"):
        env.setdefault("CDP_COOKIE_PATH", str(cookie_info["path"]))
    if effective_fingerprint:
        env.setdefault("KYL_FINGERPRINT", effective_fingerprint)
    if embedded_defaults.get("challenge_init"):
        env.setdefault("KYL_CHALLENGE_INIT_JSON", json.dumps(embedded_defaults.get("challenge_init"), ensure_ascii=False))
    if proxy:
        env.setdefault("HTTPS_PROXY", str(proxy))
        env.setdefault("HTTP_PROXY", str(proxy))
        env.setdefault("ALL_PROXY", str(proxy))

    output_lines = []
    proc = subprocess.Popen(
        cmd,
        cwd=str(runner_root),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        encoding="utf-8",
        errors="replace",
        env=env,
    )
    try:
        deadline = time.time() + timeout
        while True:
            line = ""
            if proc.stdout is not None:
                line = proc.stdout.readline()
                if line:
                    line = line.rstrip("\r\n")
                    output_lines.append(line)
                    print("[kyl] " + line, flush=True)
            if proc.poll() is not None:
                if proc.stdout is not None:
                    for line in proc.stdout:
                        line = line.rstrip("\r\n")
                        output_lines.append(line)
                        print("[kyl] " + line, flush=True)
                break
            if time.time() > deadline:
                _terminate_process_tree(proc)
                cleanup_result = cleanup_kyl_runtime_files(auth_root, [], [cookie_info.get("generated_path")]) if cleanup else {"ok": True, "removed": []}
                return {
                    "ok": False,
                    "error": "kyl_protocol_timeout",
                    "timeout": timeout,
                    "cleanup": cleanup_result,
                    "output_tail": output_lines[-20:],
                }
            if not line:
                time.sleep(0.1)
    finally:
        with contextlib.suppress(Exception):
            if proc.stdout is not None:
                proc.stdout.close()

    exit_code = int(proc.returncode or 0)
    generated = _changed_token_files(auth_root, before, started)
    if not generated and auth_root.exists():
        generated = sorted(auth_root.glob("*.json"))

    cleanup_result = {"ok": True, "removed": []}
    import_result = {"ok": False, "error": "import_not_started"}
    try:
        import_result = import_team_tokens(
            token_files=generated,
            target=target,
            export_dir=export_dir,
            workers=workers,
            cpa_api_url=cpa_api_url,
            cpa_api_token=cpa_api_token,
            sub2api_url=sub2api_url,
            sub2api_token=sub2api_token,
            sub2api_email=sub2api_email,
            sub2api_password=sub2api_password,
            sub2api_group=sub2api_group,
            sub2api_group_ids=sub2api_group_ids,
            sub2api_proxy=sub2api_proxy,
            sub2api_proxy_id=sub2api_proxy_id,
            sub2api_priority=sub2api_priority,
            sub2api_concurrency=sub2api_concurrency,
            source="KYL Protocol Runner",
        )
    finally:
        if cleanup:
            cleanup_result = cleanup_kyl_runtime_files(auth_root, generated, [cookie_info.get("generated_path")])

    return {
        "ok": exit_code == 0 and bool(import_result.get("ok")),
        "channel": TEAM_CHANNEL_KYL_PROTOCOL,
        "runner": str(runner_root),
        "exit_code": exit_code,
        "generated_token_files": [str(path) for path in generated],
        "cookie_source": cookie_info.get("source", ""),
        "fingerprint_source": cookie_info.get("fingerprint_source", "arg" if fingerprint else ""),
        "import": import_result,
        "cleanup": cleanup_result,
        "output_tail": output_lines[-20:],
    }


def import_team_token_file(
    path,
    target="cpa",
    normalized_dir=None,
    export_dir="",
    cpa_api_url="",
    cpa_api_token="",
    sub2api_url="",
    sub2api_token="",
    sub2api_email="",
    sub2api_password="",
    sub2api_group="",
    sub2api_group_ids=None,
    sub2api_proxy="",
    sub2api_proxy_id=None,
    sub2api_priority=None,
    sub2api_concurrency=None,
    source="ChatGPT_team.py",
):
    source_path = Path(path)
    raw = _read_json(source_path)
    session_data = normalize_team_token(raw, fallback_email=source_path.stem, source=source)
    if not session_data.get("access_token"):
        return {"ok": False, "path": str(source_path), "email": session_data.get("email", ""), "error": "missing_access_token"}

    normalized_dir = Path(normalized_dir) if normalized_dir else _normalized_dir(export_dir)
    normalized_dir.mkdir(parents=True, exist_ok=True)
    normalized_path = normalized_dir / f"team-{_safe_name(session_data.get('email') or source_path.stem)}.json"
    normalized_path.write_text(json.dumps(session_data, ensure_ascii=False, indent=2), encoding="utf-8")
    upsert_account(session_data, json_path=str(normalized_path))

    result = import_account_session(
        target,
        email=session_data.get("email", ""),
        session_file=str(normalized_path),
        export_dir=export_dir,
        refresh=False,
        cpa_api_url=cpa_api_url,
        cpa_api_token=cpa_api_token,
        sub2api_url=sub2api_url,
        sub2api_token=sub2api_token,
        sub2api_email=sub2api_email,
        sub2api_password=sub2api_password,
        sub2api_group=sub2api_group,
        sub2api_group_ids=sub2api_group_ids,
        sub2api_proxy=sub2api_proxy,
        sub2api_proxy_id=sub2api_proxy_id,
        sub2api_priority=sub2api_priority,
        sub2api_concurrency=sub2api_concurrency,
    )
    return {
        "ok": bool(result.get("ok")),
        "email": session_data.get("email", ""),
        "source_path": str(source_path),
        "json_path": str(normalized_path),
        "refresh_token_status": session_data.get("refresh_token_status", ""),
        "import": result,
        "error": result.get("error") or result.get("message", ""),
    }


def normalize_team_token(data, fallback_email="", source="ChatGPT_team.py"):
    data = data if isinstance(data, dict) else {}
    email = _first(data.get("email"), fallback_email)
    refresh_token = _first(
        data.get("refresh_token"),
        data.get("oauth_refresh_token"),
        _nested(data, "token", "refresh_token"),
        _nested(data, "credentials", "refresh_token"),
        _nested(data, "codex_session", "refresh_token"),
    )
    access_token = _first(
        data.get("access_token"),
        data.get("accessToken"),
        _nested(data, "token", "access_token"),
        _nested(data, "token", "accessToken"),
        _nested(data, "credentials", "access_token"),
        _nested(data, "codex_session", "access_token"),
    )
    id_token = _first(
        data.get("id_token"),
        data.get("idToken"),
        _nested(data, "token", "id_token"),
        _nested(data, "credentials", "id_token"),
        _nested(data, "codex_session", "id_token"),
    )
    now = int(time.time())
    normalized = dict(data)
    normalized.update(
        {
            "success": True,
            "status": "success",
            "type": "codex",
            "email": email,
            "access_token": access_token,
            "id_token": id_token,
            "refresh_token": refresh_token,
            "oauth_refresh_token": refresh_token,
            "refresh_token_status": "oauth_present" if refresh_token else "no_rt",
            "refresh_token_updated_at": now if refresh_token else 0,
            "refreshed_at": now,
            "team_token_import": {
                "source": source,
                "token_source": str(data.get("token_source") or ""),
                "saved_at": str(data.get("saved_at") or ""),
                "imported_at": now,
            },
        }
    )
    normalized.pop("error", None)
    return normalized


def discover_team_token_files(token_dir="", token_files=None, token_file_list=""):
    paths = []
    for item in token_files or []:
        if str(item or "").strip():
            paths.append(Path(str(item).strip()))
    if token_file_list:
        list_path = Path(token_file_list)
        if list_path.exists():
            for line in list_path.read_text(encoding="utf-8-sig", errors="replace").splitlines():
                value = line.strip().strip('"')
                if value:
                    paths.append(Path(value))
    if token_dir:
        directory = Path(token_dir)
    else:
        directory = Path.cwd() / "codex_tokens"
        if not directory.exists():
            directory = Path(__file__).resolve().parent.parent / "codex_tokens"
    if directory.exists() and directory.is_dir():
        paths.extend(sorted(directory.glob("*.json")))

    result = []
    seen = set()
    for path in paths:
        resolved = path.expanduser()
        key = str(resolved).lower()
        if key in seen or not resolved.exists() or not resolved.is_file():
            continue
        seen.add(key)
        result.append(resolved)
    return result


def _normalized_dir(export_dir=""):
    base = Path(export_dir) if export_dir else output_dir(CFG) / "team_tokens"
    return base


def _read_json(path):
    return json.loads(Path(path).read_text(encoding="utf-8-sig"))


def _first(*values):
    for value in values:
        text = str(value or "").strip()
        if text:
            return text
    return ""


def _nested(data, section, key):
    value = data.get(section) if isinstance(data, dict) else {}
    if not isinstance(value, dict):
        return ""
    return value.get(key, "")


def _safe_name(value):
    text = str(value or "unknown").strip()
    return "".join(ch if ch.isalnum() or ch in "_.@+-" else "_" for ch in text)


def cleanup_team_runtime_files(script_cwd):
    root = Path(script_cwd).resolve()
    targets = []
    for dirname in ("codex_tokens", "chatgpt_sessions"):
        directory = root / dirname
        if not directory.exists() or not directory.is_dir():
            continue
        for path in directory.glob("*.json"):
            targets.append(path)
    removed = []
    failed = []
    for path in targets:
        try:
            resolved = path.resolve()
            if root not in resolved.parents:
                failed.append({"path": str(path), "error": "outside_team_script_dir"})
                continue
            path.unlink()
            removed.append(str(path))
        except Exception as exc:
            failed.append({"path": str(path), "error": str(exc)})
    for dirname in ("codex_tokens", "chatgpt_sessions"):
        directory = root / dirname
        with contextlib.suppress(Exception):
            if directory.exists() and not any(directory.iterdir()):
                directory.rmdir()
    return {"ok": not failed, "removed": removed, "failed": failed}


def cleanup_kyl_runtime_files(auth_root, generated_files=None, extra_files=None):
    root = Path(auth_root).resolve()
    targets = []
    for item in generated_files or []:
        path = Path(item)
        if path.exists() and path.is_file():
            targets.append(path)
    for item in extra_files or []:
        if not item:
            continue
        path = Path(item)
        if path.exists() and path.is_file():
            targets.append(path)
    removed = []
    failed = []
    for path in targets:
        try:
            resolved = path.resolve()
            if resolved == root or (root not in resolved.parents and resolved.parent != root.parent):
                failed.append({"path": str(path), "error": "outside_kyl_runtime_dir"})
                continue
            path.unlink()
            removed.append(str(path))
        except Exception as exc:
            failed.append({"path": str(path), "error": str(exc)})
    with contextlib.suppress(Exception):
        if root.exists() and not any(root.iterdir()):
            root.rmdir()
    return {"ok": not failed, "removed": removed, "failed": failed}


def _prepare_kyl_cookie_path(cookie_path="", har_path="", runtime_root=None):
    if cookie_path:
        path = Path(cookie_path).expanduser()
        if path.exists() and path.is_file():
            return {"source": "cookie_file", "path": str(path)}
    if not har_path:
        return {"source": "", "path": ""}
    har = Path(har_path).expanduser()
    if not har.exists() or not har.is_file():
        return {"source": "har_missing", "path": ""}
    runtime = Path(runtime_root or (runtime_dir(CFG) / "kyl_protocol")).resolve()
    runtime.mkdir(parents=True, exist_ok=True)
    out = runtime / "cookies_from_har.json"
    cookies = _extract_cdp_cookies_from_har(har)
    fingerprint = _extract_kyl_fingerprint_from_har(har)
    out.write_text(json.dumps({"cookies": cookies}, ensure_ascii=False, indent=2), encoding="utf-8")
    return {
        "source": "har",
        "path": str(out),
        "generated_path": str(out),
        "count": len(cookies),
        "fingerprint": fingerprint,
        "fingerprint_source": "har" if fingerprint else "",
    }


def _extract_cdp_cookies_from_har(har_path):
    data = json.loads(Path(har_path).read_text(encoding="utf-8-sig", errors="replace"))
    entries = ((data.get("log") or {}).get("entries") or []) if isinstance(data, dict) else []
    result = []
    seen = set()

    def add(name, value, domain, path="/"):
        if not name or value is None or not domain:
            return
        item = {
            "name": str(name),
            "value": str(value),
            "domain": str(domain),
            "path": str(path or "/"),
        }
        key = (item["name"], item["domain"], item["path"])
        if key in seen:
            return
        seen.add(key)
        result.append(item)

    for entry in entries:
        req = entry.get("request") or {}
        resp = entry.get("response") or {}
        host = urlsplit(str(req.get("url") or "")).hostname or ""
        domain = "." + host if host and not host.startswith(".") else host
        for cookie in req.get("cookies") or []:
            add(cookie.get("name"), cookie.get("value"), cookie.get("domain") or domain, cookie.get("path") or "/")
        for cookie in resp.get("cookies") or []:
            add(cookie.get("name"), cookie.get("value"), cookie.get("domain") or domain, cookie.get("path") or "/")
        for header in req.get("headers") or []:
            if str(header.get("name") or "").lower() != "cookie":
                continue
            jar = SimpleCookie()
            with contextlib.suppress(Exception):
                jar.load(str(header.get("value") or ""))
                for morsel in jar.values():
                    add(morsel.key, morsel.value, domain, "/")
    return result


def _extract_kyl_fingerprint_from_har(har_path):
    data = json.loads(Path(har_path).read_text(encoding="utf-8-sig", errors="replace"))
    entries = ((data.get("log") or {}).get("entries") or []) if isinstance(data, dict) else []

    def scan_text(value):
        text = str(value or "")
        if not text:
            return ""
        with contextlib.suppress(Exception):
            parsed = json.loads(text)
            if isinstance(parsed, dict):
                direct = str(parsed.get("fingerprint") or parsed.get("kyl_fingerprint") or "").strip()
                if direct:
                    return direct
        m = re.search(r"kyl-fp-[A-Za-z0-9_.:-]+", text)
        if m:
            return m.group(0)
        m = re.search(r'"fingerprint"\s*:\s*"([^"]+)"', text)
        return m.group(1) if m else ""

    # Prefer the request body sent to the KYL restore endpoint.
    for entry in entries:
        req = entry.get("request") or {}
        url = str(req.get("url") or "")
        if "invite.kyl23333.xyz/api/v1/challenge/restore" not in url and "/api/v1/challenge/restore" not in url:
            continue
        post_data = req.get("postData") or {}
        found = scan_text(post_data.get("text") if isinstance(post_data, dict) else "")
        if found:
            return found

    # Fall back to scanning request/response bodies in order.
    for entry in entries:
        req = entry.get("request") or {}
        resp = entry.get("response") or {}
        post_data = req.get("postData") or {}
        found = scan_text(post_data.get("text") if isinstance(post_data, dict) else "")
        if found:
            return found
        content = resp.get("content") or {}
        found = scan_text(content.get("text") if isinstance(content, dict) else "")
        if found:
            return found
    return ""


def _load_embedded_kyl_defaults():
    path = Path(default_kyl_runner_dir()) / "embedded_kyl_defaults.py"
    if not path.exists() or not path.is_file():
        return {"fingerprint": "", "cookies": []}
    try:
        spec = importlib.util.spec_from_file_location("_embedded_kyl_defaults", str(path))
        if spec is None or spec.loader is None:
            return {"fingerprint": "", "cookies": []}
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        cookies = getattr(module, "CDP_COOKIES", []) or []
        if not isinstance(cookies, list):
            cookies = []
        return {
            "fingerprint": str(getattr(module, "KYL_FINGERPRINT", "") or "").strip(),
            "cookies": cookies,
            "challenge_init": getattr(module, "KYL_CHALLENGE_INIT", {}) or {},
        }
    except Exception:
        return {"fingerprint": "", "cookies": []}


def _write_embedded_kyl_cookies(defaults, runtime_root):
    cookies = defaults.get("cookies") or []
    if not cookies:
        return {"source": "embedded", "path": "", "count": 0}
    runtime = Path(runtime_root or (runtime_dir(CFG) / "kyl_protocol")).resolve()
    runtime.mkdir(parents=True, exist_ok=True)
    out = runtime / "cookies_embedded.json"
    out.write_text(json.dumps({"cookies": cookies}, ensure_ascii=False, indent=2), encoding="utf-8")
    return {
        "source": "embedded",
        "path": str(out),
        "generated_path": str(out),
        "count": len(cookies),
    }


def _snapshot_token_files(directory):
    result = {}
    if not directory.exists() or not directory.is_dir():
        return result
    for path in directory.glob("*.json"):
        with contextlib.suppress(Exception):
            stat = path.stat()
            result[str(path.resolve()).lower()] = (stat.st_mtime, stat.st_size)
    return result


def _changed_token_files(directory, before, started):
    if not directory.exists() or not directory.is_dir():
        return []
    changed = []
    for path in sorted(directory.glob("*.json")):
        try:
            stat = path.stat()
            key = str(path.resolve()).lower()
            old = before.get(key)
            if old is None or old != (stat.st_mtime, stat.st_size) or stat.st_mtime >= started - 2:
                changed.append(path)
        except Exception:
            continue
    return changed


def _quote_arg(value):
    text = str(value)
    if re.search(r"\s", text):
        return '"' + text.replace('"', '\\"') + '"'
    return text


def _node_executable():
    return os.environ.get("NODE") or os.environ.get("NODE_EXE") or "node"


def _sanitize_kyl_command(cmd):
    safe = list(cmd)
    for i, value in enumerate(safe[:-1]):
        if str(value) == "--fingerprint":
            raw = str(safe[i + 1])
            safe[i + 1] = raw[:18] + "..." if raw else ""
    return safe


def _terminate_process_tree(proc):
    if os.name == "nt":
        with contextlib.suppress(Exception):
            subprocess.run(["taskkill", "/F", "/T", "/PID", str(proc.pid)], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=10)
            return
    with contextlib.suppress(Exception):
        proc.kill()
